### ISSUE TITLE
Error when attempt to run the docker-compose (KeyError : MONGODB_USERNAME)

### ISSUE THREAD

**Issue by f0x-Tro0t** [Zeecka/AperiSolve#33]
It seems that an environment variable is missing in the docker compose. 
The error looks like this 

```
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/bin/flask", line 8, in <module>
web_1      |     sys.exit(main())
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 995, in main
web_1      |     cli.main(args=sys.argv[1:])
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
web_1      |     return super().main(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
web_1      |     rv = self.invoke(ctx)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
web_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
web_1      |     return ctx.invoke(self.callback, **ctx.params)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
web_1      |     return __callback(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
web_1      |     return ctx.invoke(f, obj, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
web_1      |     return __callback(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 850, in run_command
web_1      |     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 325, in __init__
web_1      |     self._load_unlocked()
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 351, in _load_unlocked
web_1      |     self._app = rv = self.loader()
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 407, in load_app
web_1      |     app = locate_app(self, import_name, name)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
web_1      |     __import__(module_name)
web_1      |   File "/app/app.py", line 23, in <module>
web_1      |     app.config["MONGO_URI"] = 'mongodb://' + os.environ['MONGODB_USERNAME']
web_1      |   File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
web_1      |     raise KeyError(key) from None
web_1      | KeyError: 'MONGODB_USERNAME'
mongodb    | 2023-03-17T14:58:39.010+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
web_1      |  * Serving Flask app 'app.py' (lazy loading)
web_1      |  * Environment: development
web_1      |  * Debug mode: on
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/bin/flask", line 8, in <module>
web_1      |     sys.exit(main())
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 995, in main
web_1      |     cli.main(args=sys.argv[1:])
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 601, in main
web_1      |     return super().main(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
web_1      |     rv = self.invoke(ctx)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
web_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
web_1      |     return ctx.invoke(self.callback, **ctx.params)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
web_1      |     return __callback(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
web_1      |     return ctx.invoke(f, obj, *args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
web_1      |     return __callback(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 850, in run_command
web_1      |     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 325, in __init__
web_1      |     self._load_unlocked()
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 351, in _load_unlocked
web_1      |     self._app = rv = self.loader()
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 407, in load_app
web_1      |     app = locate_app(self, import_name, name)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 260, in locate_app
web_1      |     __import__(module_name)
web_1      |   File "/app/app.py", line 23, in <module>
web_1      |     app.config["MONGO_URI"] = 'mongodb://' + os.environ['MONGODB_USERNAME']
web_1      |   File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
web_1      |     raise KeyError(key) from None
web_1      | KeyError: 'MONGODB_USERNAME'

```

**Comment by Zeecka** [comment]
I can reproduce by overwriting `.env` file with an empty file.
`MONGODB_USERNAME` is set in https://github.com/Zeecka/AperiSolve/blob/master/.env , you may have overwrite it ?
I'm closing the issue since `docker compose build` is working well on my side.

**Comment by SuryaMaulana** [comment]
aperisolve_back | KeyError: 'MONGODB_USERNAME' 

i have same error, I didn't change anything in the .env file or anything else
